# -*- coding: utf-8 -*-
"""Insight.pynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VterQ7c1bANhoashWIGLZBmYTLqUbvYy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
file = files.upload()

df = pd.read_csv('censustract-00-10.csv')

df.head()

df['PPCHG'].dtypes

def my_code(dt):
  dt['PPCHG'] = pd.to_numeric(dt['PPCHG'], errors='coerce')
  my_list = set(dt['TRACT10'])
  Total_Census_tracts =len(my_list)
  Total_Population_2000 = sum(df['POP00'])
  Total_Population_2010 = sum(df['POP10'])
  Average_Percentage_Change = dt['PPCHG'].mean()
  df_1 = Total_Census_tracts, Total_Population_2000, Total_Population_2010, Average_Percentage_Change
  return df_1

df_new =df.groupby(['CBSA09','CBSA_T']).apply(my_code)

print(df_new)

df_new = df_new.sort_index(ascending=True)

df_new.to_csv('report.csv',index=False)